analyzer:
  errors:
    always_put_required_named_parameters_first: ignore
    avoid_print: ignore
    non_constant_identifier_names: ignore
    sort_constructors_first: ignore
include: package:dart_frog_lint/recommended.yaml
